- name: configure create
  hosts: cart
  become: yes
  tasks:
  - name: enable nodejs 20 # command module
    ansible.builtin.command: dnf module enable nodejs:20 -y


  - name: install nodejs # dnf module
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: create system user roboshop #create sysytem user module
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"

  - name: delete app directory #delete directory module
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory # Create directory module
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: delete cart zip file # delete zip file module
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent

  - name: Download cart file # Download cart file using url module
    ansible.bul.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      path: /tmp/cart.zip

  - name: unarchieve file #un zip flie module
    ansible.builtin.unarchieve:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: inatall dependencies # npm dependency module
    community.general.npm:
      path: /app
  
  - name: copy cart service # copy or templete module
    ansible.builtin.template:
      src: cart.service
      dest: /etc/systemd/system/cart.service
  
  - name: daemon reload   # system service demon reloaded module
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start cart
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes